config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'admin/orders'
  get 'admin/concretar_orden'
  get 'admin/products'
  get 'admin/show_order'
  get 'admin/show_product'
  delete 'admin/index'
  get 'cart/confirmar'
  get 'cart/show'
  devise_for :users
  resources :orders
  resources :products
  resources :order_items
  resources :cart
  root "products#index" 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    if user_signed_in? && current_user.client?
      @order_items = current_order.order_items
    else
      redirect_to new_user_session_path, alert: "Debes iniciar sesion para ver tu carrito "
    end

  end

  def confirmar
    order=current_user.orders.last
    order.status=1
    order.fecha_confirmacion=Time.now
    order.save
    current_order= current_user.orders.new(status: 0, user_id: current_user.id)
    current_order.save
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_carts.html.erb
<%=link_to "#{current_order.order_items.size} productos acumulados con el valor de $#{current_order.subtotal}", cart_show_path%>

app/views/cart/_carts_item.html.erb
<% @order_items.each do |item|%>
<div class="accordion" id="accordionExample" style="padding:2%">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%=item.product.id%>" aria-expanded="true" aria-controls="collapseOne">
          <%= item.product.name%>
      </button>
    </h2>
  <div id="collapse<%=item.product.id%>" class="accordion-collapse collapse hidden" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
  <div class="accordion-body">
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">  
        <%if item.product.image.attached? %>
          <%= image_tag item.product.image , class:"img-fluid img-thumbnail rounded-start", style:'width:200px; height:200px'%>
        <%else%>
          <%= image_tag "no_image.png",class:'img-fluid rounded-start' %>
        <%end%>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5>Descripcion: <%= item.product.description%></h5>
          <h5>Modelo: <%= item.product.model%></h5>
          <h5>Marca:<%= item.product.brand%></h5>
          <h5>Precio unitario: $<%= item.product.price.to_i%></h5>
          <%= form_for item, remote: true do |f| %>
          <div class="input-group mb-2">
            <%= f.hidden_field :product, :value => item.product.id%>
            <%= f.number_field :quantity, :value => item.quantity.to_i, class:'form-control form-control-sm'%>
            <%= f.submit "Actualizar carrito",  class:'btn btn-sm btn-outline-dark'%>
          </div>
          <h5>Subtotal: $<%= item.total.to_i%></h5>
            <%= link_to "Quitar producto", order_item_path(item), method: :delete, remote: true, class:'btn btn-sm btn-outline-danger'%>
          <%end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>
<% end %>

<div class="row justify-content-md-center mt-3">
<div class="col-md-auto">
  <div class="input-group mb-3">
    <input type="text" class="form-control" placeholder="El total del carrito es de $<%= current_order.subtotal.to_i%>"  disabled>
    <%=link_to 'Pagar', cart_confirmar_path, class:'btn btn-success'%>
    <%=link_to 'Seguir comprando', root_path, class:'btn btn-outline-secondary'%>
  </div>
</div>
</div>

app/views/cart/confirmar.html.erb
<div class="alert alert-primary" role="alert">
  La orden se genero correctamente, para verla haga click  <a href="<%= order_path(current_user.orders[-2]) %>" class="alert-link">aqui</a>
</div>

app/views/cart/show.html.erb
<div class="text-center"><h1>Carrito de compras</h1></div>
<div class="carts_item">
  <%= render 'carts_item'%>
</div>