config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'admin/orders'
  get 'admin/concretar_orden'
  get 'admin/products'
  get 'admin/show_order'
  get 'admin/show_product'
  delete 'admin/index'
  get 'cart/confirmar'
  get 'cart/show'
  devise_for :users
  resources :orders
  resources :products
  resources :order_items
  resources :cart
  root "products#index" 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/index.html.erb
<div style="padding:1%">
  <ul class="nav nav-pills nav-fill">
    <li class="nav-item ">
      <a class="nav-link" href="<%= admin_orders_path%>">Ordenes</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<%= admin_products_path%>">Productos</a>
    </li>
   </ul>
   <div class="card padding:2%">
  <h3 class="text-center">Ultimas ordenes</h3>
  <div class="row row-cols-1 row-cols-md-2 g-4 ">
  <div class="col ">
    <div class="card mx-3 my-3">
      <div class="card-body">
        <h5 class="card-title">Orden n° <%= @ultimas_ordenes[0].first.id%></h5>
        <p class="card-text">Monto: $<%=@ultimas_ordenes[0].first.subtotal.to_i %>
        <p class="card-text">Estado: <%=@ultimas_ordenes[0].first.status.humanize %></p>
        <%= link_to 'Detalles', admin_show_order_path(:id => @ultimas_ordenes[0].first.id), class:'btn btn-sm btn-outline-primary' %>        
      </div>
    </div>
  </div>
  <div class="col ">
    <div class="card mx-3 my-3">
      <div class="card-body">
        <h5 class="card-title">Orden n° <%= @ultimas_ordenes[1].id%></h5>
        <p class="card-text">Monto: $<%=@ultimas_ordenes[1].subtotal.to_i %>      
        <p class="card-text">Estado: <%=@ultimas_ordenes[1].status.humanize %></p>
        <%= link_to 'Detalles', admin_show_order_path(:id => @ultimas_ordenes[1].id), class:'btn btn-sm btn-outline-primary' %>
      </div>
    </div>
  </div>
  
</div>
</div>
</div>

app/views/admin/orders.html.erb
<div card="card" style="padding:1%">
  <table class="table table-striped table-hover">
    <thead class="table-dark">
      <tr>
        <th scope="col">ID de orden</th>
        <th scope="col">Estado</th>
        <th scope="col">Precio de la orden</th>
        <th scope="col" style="width:10%"></th>
      </tr>
    </thead>
    <tbody>
      <%@orders.each do |order|%>
      <tr>
        <td> <%=order.id%></td>
        <% case order.status%>
          <%when 'cancelada'%>
          <td class="text-danger"><%= order.status.humanize%></td>
          <%when 'confirmada'%>
          <td class="text-primary"><%= order.status.humanize%></td>
          <%when 'pagada'%>
          <td class="text-success"><%= order.status.humanize%></td>
          <%when 'sin_confirmar'%>
          <td class="text-secondary"><%= order.status.humanize%></td>
          <%else%>
          <td>Estado invalido</td>
        <%end%>
        <td>$<%= order.subtotal.to_i %></td>
        <td><div class="btn-group">
        <%= link_to 'Aceptar', admin_concretar_orden_path(:id => order.id) , class: 'btn btn-sm btn-outline-success'%>
        <%= link_to 'Detalles', admin_show_order_path(:id => order.id), class:'btn btn-sm btn-outline-primary' %>
        <%= link_to 'Eliminar', order ,method: :delete, data: {confirm:'¿Esta seguro de cancelar la orden?'}, class:'btn btn-sm btn-outline-danger'%>
        </div>
        </td>
        
      </tr>
    <%end%>
    </tbody>
  </table>
</div>
<div class="text-center">
<%= link_to 'Atras', admin_index_path, class:'btn btn-outline-secondary mt-3'%>
</div>

app/views/admin/products.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <h1>Mis Productos</h1>
</div>
  <div class="text-center mb-3">
    <%= link_to 'Agregar Producto', new_product_path , class:'btn btn-outline-success'%>
  </div>
  <div card="card" style="padding:1%">
  <table class="table table-striped table-hover">
    <thead class="table-dark">
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Precio</th>
        <th scope="col">Modelo</th>
        <th scope="col">Marca</th>
        <th scope="col">Descripcion</th>
        <th scope="colspan-3" style="width:10%"></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td ><%= product.name%></td>
          <td>$<%= product.price.to_i%></td>
          <td><%= product.model %></td>
          <td><%= product.brand %></td>
          <td><%= product.description %></td>
          <td><div class="btn-group" role="group">
            <%= link_to 'Detalles', admin_show_product_path(:id => product.id), class:'btn btn-outline-primary' %>
            <%= link_to 'Editar', edit_product_path(product),class:'btn btn-outline-primary' %>
            <%= link_to 'Eliminar', product ,method: :delete, data: {confirm:'¿Esta seguro?'}, class:'btn btn-outline-danger'%>
          </div></td>
        </tr>
      <% end %>
      </tbody>
    </table>
</div>

<div class="text-center">
<%= link_to 'Atras', admin_index_path, class:'btn btn-outline-secondary mt-3'%>
</div>

app/views/admin/show_order.html.erb
<div class="text-center">
  <h1>Orden n° <%= @order.id%></h1>
</div>

<% @order.order_items.each do |item|%>
<div class="accordion" id="accordionExample" style="padding:2%">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%=item.product.id%>" aria-expanded="true" aria-controls="collapseOne">
          <%= item.product.name%>
      </button>
    </h2>
  <div id="collapse<%=item.product.id%>" class="accordion-collapse collapse hidden" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
  <div class="accordion-body">
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">  
        <%if item.product.image.attached? %>
          <%= image_tag item.product.image , class:"img-fluid img-thumbnail rounded-start", style:'width:200px; height:200px'%>
        <%else%>
          <%= image_tag "no_image.png",class:'img-fluid rounded-start' %>
        <%end%>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5>Descripcion: <%= item.product.description%></h5>
          <h5>Modelo: <%= item.product.model%></h5>
          <h5>Marca:<%= item.product.brand%></h5>
          <h5>Precio unitario: $<%= item.product.price.to_i%></h5>
          <h5>Cantidad: <%= item.quantity%>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>
</div>
<% end %>
<div style="padding:2%">
  <div class="card text-center mt-3">
    <div class="card-header">
      Datos de la orden
    </div>
    <div class="card-body">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Total de la orden: $<%= @order.subtotal.to_i%></li>
        <li class="list-group-item">Titular de la orden: <%= @order.user.name%> <%= @order.user.lastname%></li>
        <li class="list-group-item">Direccion de entrega de la orden: <%= @order.user.address%></li>
      </ul>
    </div>
    <% if  @order.fecha_confirmacion.present?%>  
        <div class="card-footer text-muted">
          Generada el dia <%= @order.fecha_confirmacion.strftime("%d-%m-%Y a las %H:%M")%>
        </div>
    <% else %>
        <div class="card-footer text-muted">
          Orden sin confirmar
        </div>
    <% end %>
  </div>
</div>

app/views/admin/show_product.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <div class="card mb-3" style="max-width: 1080px;">
   <div class="row g-0">
     <div class="col-md-4">
      <%if @product.image.attached?%>
        <%=image_tag @product.image, class:"img-fluid rounded-start w-100 h-100"%>
        <%else%>
          <%= image_tag "no_image.png",class:'img-fluid rounded-start w-100 h-100', style: 'height:50vw;width:100vw;margin-bottom:20px;' %>
        <%end%>
     </div>
     <div class="col-md-8">
       <div class="card-body">
         <h5 class="card-title"><%= @product.name %></h5>
         <ul class="list-group list-group-flush">
            <li class="list-group-item">Descripcion: <%= @product.description %></li>
            <li class="list-group-item">Marca: <%= @product.brand %></li>
            <li class="list-group-item">Modelo: <%= @product.model %></li>
            <li class="list-group-item">Precio: <%= @product.price %></li>
            <li class="list-group-item">Stock: <%= @product.stock %></li>
         </ul>
        </div>
      </div>
    </div>
  </div>
       <div class="text-center mt-3"> 
           <%= link_to 'Atras', admin_products_path, class:'btn btn-outline-secondary' %>
       </div>
</div>