config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'admin/orders'
  get 'admin/concretar_orden'
  get 'admin/products'
  get 'admin/show_order'
  get 'admin/show_product'
  delete 'admin/index'
  get 'cart/confirmar'
  get 'cart/show'
  devise_for :users
  resources :orders
  resources :products
  resources :order_items
  resources :cart
  root "products#index" 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
  has_many :order_items
 




  validates :model, presence: {message: "Debe escribir el numero de modelo"}
  validates :brand, presence: {message: "Debe escribir el modelo"}
  validates :name, presence: {message: "Debe escribir un nombre"}
  validates :price, presence: {message: "Escriba un precio para el producto"}
  validates :price, numericality: { message: "El precio ingresado contiene letras" }



  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /products or /products.json
  def index
    @order_item = current_order.order_items.new if user_signed_in? && current_user.client?
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), alert: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), alert: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, alert: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :model, :brand, :stock, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="card">
  <div class="card-header">
    Informacion del producto 
  </div>
  <div class="card-body">
    <div class="form-group">
      <div class="input-group mb-3">
        <span class="input-group-text mb-3">Nombre</span>
        <%= form.text_field :name, class:'form-control mb-3' %>
      </div>
    </div>
  <div class="form-group">
    <div class="input-group mb-3">
      <span class="input-group-text mb-3">Descripcion</span>
      <%= form.text_field :description, class: 'form-control mb-3' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
      <span class="input-group-text mb-3">Modelo </span>
      <%= form.text_field :model, class:'form-control mb-3' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group mb-3">
      <span class="input-group-text mb-3">Marca</span>
      <%= form.text_field :brand, class:'form-control mb-3' %>
    </div>
  </div>

  <div class="form-group">
    <div class="input-group mb-3">
      <span class="input-group-text mb-3">Precio</span>
      <%= form.text_field :price, class:'form-control mb-3' %>
    </div>
  </div>


<div class="input-group mb-3">
  <span class="input-group-text">Presente en stock</span>
  <div class="input-group-text">
   <%= form.check_box :stock, class:'form-check-input mt-0'%>
  </div>
</div>


  <div class="form-group">
    <div class="input-group mb-3">
      <span class="input-group-text mb-3">Imagen</span>
      <%= form.file_field :image, class:'form-control mb-3'%>
    </div>
  </div>

  <div class="d-grid">
    <%= form.submit "Aceptar", class:'btn btn-lg btn-outline-success btn-login fw-bold mb-2' %>
  </div>

  </div>

  </div>
  </div>
</div>



<% end %>

app/views/products/edit.html.erb
<h1 class="text-center">Editar producto</h1>

<%= render 'form', product: @product %>

<div class="text-center mt-3">
<div class="btn-group" role="group" aria-label="Basic mixed styles example">
  <%= link_to 'Mostrar producto', @product , class:'btn btn-outline-primary'%>
  <%= link_to 'Atras', products_path, class:'btn btn-outline-secondary' %>
</div>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <h1>Productos disponibles</h1>
</div>
<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @products.each do |product| %>
     <div class="card mx-2 mt-3" style="max-width: 18rem">
        <%if product.image.attached?%>
        <%= image_tag product.image, class:"card-img-top",style:'width:300px; height:300px'%>
        <%else%>
          <%= image_tag "no_image.png",class:'card-img-top',style:'height:262px; width:262px ' %>
        <%end%>
      <div class="card-body">
        <h5 class="card-title"><%= product.name%></h5>
        <h6 class="card-subtitle mb-2 text-muted">Precio: $<%= product.price.to_i%></h6>
        <h6 class="card-subtitle mb-2 text-muted">Modelo: <%= product.model %></h6>
        <h6 class="card-subtitle mb-2 text-muted">Descripcion: <%= product.description %></h6>
        <h6 class="card-subtitle mb-2 text-muted">Marca: <%= product.brand %></h6>
        <%= link_to 'Detalles', product, class:'btn btn-outline-primary' %>
        <% if user_signed_in? && current_user.client?%>
          <%= form_for @order_item, remote: true do |f|%>
            <div class="input-group mb-3">
              <%=f.hidden_field :product_id, :value => product.id%>
              <%= f.number_field :quantity, :value => 1, :min => 1, class:'form-control form-control-sm'%>
              <%if product.stock%>
                <%= f.submit "Agregar al carrito", class:'btn btn-sm btn-outline-success'%>
              <% else %>
                <%= f.submit "Agregar al carrito", class:'btn btn-sm btn-outline-success disabled'%>
                <h6 class="text-muted">Fuera de stock</h6>
              <% end %>
            </div>
          <% end %>
        <%elsif !user_signed_in? %>
          <li class="list-group-item"><h6 class="text-muted">Debe inciar sesion para agregar items al carrito</h6></li>
        <%end%>
    </div>
    </div>
  <% end %>
</div>

   

app/views/products/new.html.erb
<h1 class="text-center">Nuevo producto</h1>

<%= render 'form', product: @product %>
<div class="text-center mt-3">
<%= link_to 'Atras', products_path, class:'btn btn-outline-secondary' %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <div class="card mb-3" style="max-width: 1080px;">
   <div class="row g-0">
     <div class="col-md-4">
      <%if @product.image.attached?%>
        <%=image_tag @product.image, class:"img-fluid rounded-start w-100 h-100"%>
        <%else%>
          <%= image_tag "no_image.png",class:'img-fluid rounded-start w-100 h-100', style: 'height:50vw;width:100vw;margin-bottom:20px;' %>
        <%end%>
     </div>
     <div class="col-md-8">
       <div class="card-body">
         <h5 class="card-title"><%= @product.name %></h5>
         <ul class="list-group list-group-flush">
           <li class="list-group-item">Descripcion: <%= @product.description %></li>
            <li class="list-group-item">Marca: <%= @product.brand %></li>
            <li class="list-group-item">Modelo: <%= @product.model %></li>
            <li class="list-group-item">Precio: $ <%= @product.price.to_i %></li>
         </ul>
        </div>
      </div>
    </div>
  </div>
       <div class="text-center mt-3"> 
           <%= link_to 'Atras', products_path, class:'btn btn-outline-secondary' %>
       </div>
</div>