config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  get 'admin/orders'
  get 'admin/concretar_orden'
  get 'admin/products'
  get 'admin/show_order'
  get 'admin/show_product'
  delete 'admin/index'
  get 'cart/confirmar'
  get 'cart/show'
  devise_for :users
  resources :orders
  resources :products
  resources :order_items
  resources :cart
  root "products#index" 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">  
  <%= alert%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_btn-cart.html.erb
<div class="dropdown mx-3">
    <a class="btn btn-secondary" href="<%= cart_show_path%>">
        <i class="fa-solid fa-cart-shopping"></i>
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="<%= cart_show_path%>">Mi carrito</a></li>
        <li><a class="dropdown-item" href="#">Eliminar carrito</a></li>
    </ul>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid"> 
    <a class="navbar-brand" >
      <i class="fa-solid fa-mobile-screen-button"></i>
    </a>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=<%= root_path%>>
            <%if user_signed_in? && current_user.admin?%>
              Vista del cliente
            <%else%>
              Pagina Principal
            <% end %>
          </a>
        </li>
        <%if user_signed_in?%>
          <%if current_user.admin?%>
            <li class="nav-item">
              <a class="nav-link" href="<%=admin_index_path%>">Mi tienda</a>
            </li>
          <%else%>
            <li class="nav-item">
              <a class="nav-link" href="<%=orders_path%>">Mis Ordenes</a>
            </li>
          <% end %>
        <%end%>
      </ul>

      <% if !user_signed_in? || current_user.client? %>
        <div class="dropdown mx-3">
          <a class="btn btn-secondary" href="<%= cart_show_path%>">
              <i class="fa-solid fa-cart-shopping"></i>
          </a>
        </div>
        <%end%>
      <%if (user_signed_in?) %>
       <div class="btn-group dropstart">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-circle-user"></i> 
            <a><%= current_user.name.humanize%></a> 
          </button>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item"><%= link_to "Editar", edit_user_registration_path, class:'dropdown-item' %></a></li>
            <li><a class="dropdown-item"><%= link_to 'Desconectarse', destroy_user_session_path , method: :delete, data: { confirm: 'Are you sure?' }, class:'dropdown-item'%></a></li>
          </ul> 
          </div>
      <%else %>
   
        <div class="btn-group dropstart">
          <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-circle-user"></i>
          </button>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= new_user_session_path%>">Iniciar sesion</a></li>
            <li><a class="dropdown-item" href="<%= new_user_registration_path%>">Registrarse</a></li>
          </ul> 
          </div>

      <%end%>
    </div>
  </div>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tienda Informatica</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5d018e5526.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%if alert %>
       <%= render 'layouts/alerts'%>
    <% end %>

  </head>

  <body>
    <%= render 'layouts/navbar'%>  
    <%= yield %>
  </body>
</html>